### ISSUE TITLE
Search with "s" leads to broken results

### ISSUE THREAD

**Issue by fractaledmind** [bridgetownrb/bridgetown-quick-search#25]
In searching the string `logic of s`, I got these results:

<img width="537" alt="CleanShot 2024-04-30 at 12 20 23@2x" src="https://github.com/bridgetownrb/bridgetown-quick-search/assets/5077225/116df488-65b9-4101-baf8-2dedebd25c48">

**Comment by jaredcwhite** [comment]
I can't repro on the Bridgetown site's search. If you can provide a test case, I'm happy to take a look at it!
