### ISSUE TITLE
For prototype pages, no `content` is included in index

### ISSUE THREAD

**Issue by stevegeek** [bridgetownrb/bridgetown-quick-search#3]
I think what I'm seeing here is for any Prototype pages, the `content` attribute in the generated Json index is blank, implying `document.content` is blank for these pages when the index is generated

```
        {
          "id": "my-article",
          "title": "Title",
          "collection": {
            "label": "notes",
            "name": "Posts"
          },
          "categories": "notes",
          "tags": "",
          "url": "/my-article/",
          "content": ""
        },
```

**Comment by jaredcwhite** [comment]
Sorry I'm replying to this so late!

I'm not sure we even want prototype pages (aka paginated archives, category, tags, etc.) in the search index TBH, and I might explicitly enforce that. Was there something in particular about a prototype page where you want it to show up for searches?

**Comment by stevegeek** [comment]
No problem. To be honest... I don't remember! I think it makes sense that they are excluded from the index.

**Comment by jaredcwhite** [comment]
Cool, I think I'll tighten that up then and document that we'll only be indexing individual resources going forward.
